src/cocatr2/config/routes.rb
Rails.application.routes.draw do
  resources :listings do
    resources :reviews, only:[:new, :create, :index, :edit, :destroy, :update, :show]
    patch 'applications/:id/update', to: "applications#update_app", as: "update_app"
    resources :applications, only: [:new, :create]
  end

  resources :applications, only: [:edit, :update, :my_apps]

  get '/my_listings', to: 'listings#my_listings', as: "my_listings"
  get '/my_apps', to: 'applications#my_apps', as: "my_apps"
  patch '/listings/:id/update', to: "listings#update_listing", as: "update_listing"


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#page'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/cocatr2/app/views/partials/_application_cards.html.erb
<% @applications.each do |a| %>
    <div class="card w-75 bg-light">
        <div class="card-body">
            <h5 class="card-title text-dark"><%= a.subject %></h5>
            <h6>
                <% if a.status == "Approved"%>
                    <span class="badge bg-success text-light">Status: <%= a.status %></span>
                <% elsif a.status == "Declined"%>
                    <span class="badge bg-danger text-light">Status: <%= a.status %></span>
                <% else %>
                    <span class="badge bg-warning text-dark">Status: <%= a.status %></span>
                <% end %>
                <span class="badge bg-dark text-light">User: <%= a.user.username %></span>
            </h6>
            <p class="card-text"><%= a.message %></p>
            <p class="card-text">
                <small class="text-muted">Last updated <%= time_ago_in_words(a.updated_at)%> ago.</small>
            </p>
            <% if a.application_type == "Application" %>
                <% if a.listing.user == current_user %>
                    <% if a.status == "Pending" %>
                        <%= link_to 'Accept', listing_update_app_path(a.listing, a.id , status: "Approved"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'  %>
                        <%= link_to 'Decline', listing_update_app_path(a.listing, a.id , status: "Declined"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
                    <% elsif a.status == "Approved" %>
                        <%= link_to 'Complete', listing_update_app_path(a.listing, a.id , status: "Closed"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'  %>
                        <%= link_to 'Cancel', listing_update_app_path(a.listing, a.id , status: "Declined"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
                    <% end %>
                <% elsif a.user == current_user %>
                    <%= link_to 'Delete', listing_update_app_path(a.listing, a.id , status: "Archived"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
                <% end %>
                
            <% elsif a.application_type == "Report" %>
                <%= link_to 'Listing', listings_path, class: 'btn btn-primary btn-sm' %>
                <%= link_to 'User', listings_path, class: 'btn btn-dark text-light btn-sm' %>
                <%= link_to 'Accept', listing_update_app_path(a.listing, a.id , status: "Closed"), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
            <% end %>
        </div>

        <% if false%>
            <img class="card-img-bottom" src="..." alt="Card image cap">
        <% end %>
    </div>
<% end %>

src/cocatr2/app/views/partials/_cards.html.erb
<% @listings.each do |a| %>
    <div class="card w-75 bg-light">
        <div class="card-body">
            <div class="card-title text-dark inline">
              <h5>
                <span class="badge bg-secondary text-light"><%= a.listing_type %></span>    
                <%= link_to a.title, a %>

              </h5>
            </div>
            <h6>
                <span class="badge bg-light text-dark">Game: <%= a.game %></span>
                <span class="badge bg-light text-dark">User: <%= a.user.username %></span>
                <span class="badge bg-light text-dark">Avg: <%= a.average_rating %></span>
            </h6>
            <p class="card-text"><%= a.description %></p>
            <p class="card-text">
                <% if a.user == current_user %>
                  <% if a.applications.where(status: 'Pending').where(application_type: 'Application').count > 0%>
                    <span class="badge bg-warning text-dark">!</span>
                  <% end %>
                  <% if a.status == "Open"%>
                    <span class="badge bg-success">Open</span>
                  <% elsif a.status == "Closed" %>
                    <span class="badge bg-danger">Closed</span>
                  <% end %>
                <% end %>
                <small class="text-muted">Last updated <%= time_ago_in_words(a.updated_at)%> ago.</small>
                <%= link_to "Show", a, class: 'btn btn-primary btn-sm' %>
            </p>
        </div>

        <% if a.listing_picture.attached? %>
          <%= image_tag a.listing_picture, class: "card-img-bottom" %>
        <% end %>
    </div>
<% end %>

src/cocatr2/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary bg-gradient">
  <a class="navbar-brand" href="#">CoCaTr</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleContent" aria-controls="navrbarToggleContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarToggleContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
            <%= link_to "Home", root_path, method: :get, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "Browse", listings_path, method: :get, class: "nav-link"%>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "New", new_listing_path, method: :get, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "My Applications", my_apps_path, method: :get, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "My Listings", my_listings_path, method: :get, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%#= link_to "Profile", root_path, method: :get, class: "nav-link"%>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, method: :get, class: "nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, method: :get, class: "nav-link"%>
            </li>
        <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <div class="form-group input-group" action="index">
            <input class="form-control mr-sm-2" type="search" name="title"  placeholder="Search listings..">
            <button class="btn btn-outline-dark" type="submit">Search</button>
        </div>
    </form>
    <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-dark"%>
    <% end %> 
  </div>
</nav>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>