src/cocatr2/config/routes.rb
Rails.application.routes.draw do
  resources :listings do
    resources :reviews, only:[:new, :create, :index, :edit, :destroy, :update, :show]
    patch 'applications/:id/update', to: "applications#update_app", as: "update_app"
    resources :applications, only: [:new, :create]
  end

  resources :applications, only: [:edit, :update, :my_apps]

  get '/my_listings', to: 'listings#my_listings', as: "my_listings"
  get '/my_apps', to: 'applications#my_apps', as: "my_apps"
  patch '/listings/:id/update', to: "listings#update_listing", as: "update_listing"


  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root 'home#page'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

src/cocatr2/app/models/listing.rb
class Listing < ApplicationRecord
include Filterable
include PgSearch::Model
  belongs_to :user
  has_many :reviews
  has_many :applications
  has_one_attached :listing_picture

  # Enums define what the integer values mean, and provide an alternate way to use them
  enum listing_type: { "Coach" => 0, "Offer" => 1, "Request" => 2, "Trade" => 3 }
  enum status: { "Open" => 0, "Closed" => 1, "Archived" => 2, "Removed" => 3}

  # pg_search scope to be a bit more flexible for the search bar
  pg_search_scope :filter_by_title, against: :title

  # Regular scopes for assorted views
  scope :filter_by_status, -> (status) {where status: status}
  scope :filter_by_listing_type, -> (listing_type) {where listing_type: listing_type}
  scope :filter_by_user, -> (user) { where user: user}

  # Get the average rating of all reviews left on this listing
  def average_rating
    if self.reviews.count == 0
      return 0
    end
    rating_sum = 0.0
    self.reviews.each do |r|
      rating_sum += r.rating.to_f
    end
    return rating_sum / self.reviews.count
  end

  def pending_apps
    MyModel.where.not(status: 'reject').count
    return self.reviews.where(status: 'Pending').count
  end

end

src/cocatr2/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy update_listing ]
  before_action :authenticate_user! , only: [:new, :create, :destroy, :my_listings]

  # This modified index method accepts search params
  def index
    @listings = Listing.filter_by(params.slice(:title, :username)).filter_by_status("Open")
  end

  def my_listings
    @listings = Listing.filter_by_user(current_user)
  end

  # GET /listings/1 or /listings/1.json
  def show
    @applications = @listing.applications.filter_by_status("Pending").filter_by_application_type("Application")
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end



  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_listing
    @listing.update(status: params[:status])
    redirect_to listing_url(@listing)
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_status_param)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :listing_type, :game, :description, :status, :user_id, :listing_picture)
    end

    def listing_status_param
      params.require(:status)
    end
end

src/cocatr2/app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, required: true %>
    <%= f.input :listing_type, required: true %>
    <%= f.input :game, required: true %>
    <%= f.input :description, required: true %>
    <%= f.input :status %>
    <label class="btn btn-primary btn-sm">
      Add a picture!
      <span style="display:none;">
        <%= f.input :listing_picture, as: :file, required: true, multiple: false, accept: "image/jpg, image/png, image/jpeg" %>
      </span>
    </label>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

src/cocatr2/app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1> <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary btn-lg"  %>
  <div class="row">
    <div class="col-sm-6">
      <%= render "partials/cards" %>
    </div>
  </div>
<br>

src/cocatr2/app/views/listings/my_listings.html.erb
<p id="notice"><%= notice %></p>

<h1>My Listings</h1>
  <% if @listings.count > 0 %>
    <%= render "partials/cards" %>
  <% else %>
    <h3>You don't have any listings yet!</h3>
  <% end %>

<br>

<%= link_to 'New Listing', new_listing_path, class: "btn btn-primary btn-lg"  %>

src/cocatr2/app/views/listings/show.html.erb
<div class="card text-center" style="max-height: 75%;">
  <div class="card-header">
    <%= @listing.listing_type%> - <%= @listing.game %> - <%= @listing.average_rating%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @listing.title %></h5>
    <p class="card-text"><%= @listing.description %></p>
    <% if @listing.user == current_user %>
<%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-secondary btn-sm'  %> 
  <% if @listing.status == "Open" %>
    <%= link_to 'Close', update_listing_path(@listing, status: "Closed"), method: :patch, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm'  %>
  <% elsif @listing.status == "Closed" %>
    <%= link_to 'Open', update_listing_path(@listing, status: "Open"), method: :patch, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm'  %>
  <% end %>
<%= link_to 'Delete', update_listing_path(@listing, status: "Archived"), method: :patch, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm'  %>
<% end %>
<% if current_user.admin? %>
<%= link_to 'Remove', update_listing_path(@listing, status: "Removed"), method: :patch, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm' %>
<% end %>
<br><br>
<%= link_to 'Reviews', listing_reviews_path(@listing.id), class: 'btn btn-secondary btn-sm'  %> 
<%= link_to 'Apply Now', new_listing_application_path(@listing.id), class: 'btn btn-secondary btn-sm'  %> 
<%= link_to 'New Review', new_listing_review_path(@listing.id), class: 'btn btn-secondary btn-sm'  %> 
<%= link_to 'Back', listings_path, class: 'btn btn-secondary btn-sm' %>

  </div>
  <div class="card-footer text-muted">
    Posted by <%= @listing.user.username %> - Last updated <%= time_ago_in_words(@listing.updated_at)%> ago.
  </div>
  <% if @listing.listing_picture.attached? %>
    <%= image_tag @listing.listing_picture, class: "card-img-bottom img-fluid" %>
  <% end %>
</div>

<% if @listing.user == current_user %>
  <% if @applications.count > 0 %>
  <h4>Pending Applications</h4>
  <div class="row">
    <div class="col-sm-6">
      <%= render "partials/application_cards" %>
    </div>
  </div>
  <% end %>
<% end %>